### ISSUE TITLE
Edit Category and Edit Activity dialogues are mislabelled and confusing

### ISSUE THREAD

**Issue by densoutar** [slashroots/undp-ghg-v2#75]
Clicking "edit" in the Categories tab opens a dialog labelled "Add Category"; in the Activities tab it opens one labelled "Add Activity". Both should be relabelled to "Edit Local Category" and  to "Edit Local Activity" respectively.

When the Edit dialogues are opened, some of the fields are blank, instead of showing the existing entries. In the Category dialogue, changing a Category Code and then selecting an IPCC Category overwrites the user-generated Category Code. This should not happen. It might be best for the Category Code not to to be auto-filled at all.

The Category Code field should be relabelled "Local Category Code".

**Comment by paradoxxjm** [comment]
@denferg can you confirm that this has been addressed.

**Comment by densoutar** [comment]
@paradoxxjm  incomplete—only the dialogue labels have been changed.

**Comment by densoutar** [comment]
In the Edit Category dialogue, the existing sector and IPPC category are still not displayed

**Comment by densoutar** [comment]
Add Local Category and Edit Local Category dialogues are working as expected.
